.TH "Camera" 3 "Tue Apr 9 2013" "Version 0.1" "PIM380" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Camera \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual XnStatus \fBInit\fP (int argc, char **argv)"
.br
.ti -1c
.RI "virtual XnStatus \fBRun\fP ()"
.br
.ti -1c
.RI "void \fBcaptureSingleFrame\fP ()"
.br
.ti -1c
.RI "std::string \fBInt2Str\fP (int nb)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCamera\fP & \fBCreateInstance\fP (xn::Context &context)"
.br
.ti -1c
.RI "static void \fBDestroyInstance\fP (\fBCamera\fP &instance)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBCamera\fP (xn::Context &context)"
.br
.ti -1c
.RI "virtual int \fBDisplay\fP ()"
.br
.ti -1c
.RI "virtual void \fBDisplayPostDraw\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnKey\fP (unsigned char key, int x, int y)"
.br
.ti -1c
.RI "virtual XnStatus \fBInitOpenGL\fP (int argc, char **argv)"
.br
.ti -1c
.RI "void \fBInitOpenGLHooks\fP ()"
.br
.ti -1c
.RI "void \fBScalePoint\fP (XnPoint3D &point)"
.br
.ti -1c
.RI "void \fBglPrintString\fP (void *font, const char *str)"
.br
.ti -1c
.RI "void \fBprintHelp\fP (int nXLocation, int *pnYLocation)"
.br
.ti -1c
.RI "void \fBdrawHelpScreen\fP ()"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static \fBCamera\fP & \fBInstance\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "xn::Context & \fBm_rContext\fP"
.br
.ti -1c
.RI "xn::DepthGenerator \fBm_depth\fP"
.br
.ti -1c
.RI "xn::ImageGenerator \fBm_image\fP"
.br
.ti -1c
.RI "xn::IRGenerator \fBm_IR\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fBCamera\fP * \fBsm_pInstance\fP = NULL"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PIM380 from the source code\&.
