.TH "Color" 3 "Tue Apr 9 2013" "Version 0.1" "PIM380" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Color \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColor\fP (const \fBColor\fP &iOther)"
.br
.ti -1c
.RI "\fBColor\fP (int red, int green, int blue, int alpha=255)"
.br
.ti -1c
.RI "\fBColor\fP (const float red, const float green, const float blue, const float alpha=1\&.0f)"
.br
.ti -1c
.RI "\fBColor\fP & \fBoperator=\fP (const \fBColor\fP &iOther)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PIM380 from the source code\&.
