.TH "Config" 3 "Tue Apr 9 2013" "Version 0.1" "PIM380" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Config \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBLoadConfigs\fP (const std::string &iFilename)"
.br
.ti -1c
.RI "static const std::string & \fBRootPath\fP ()"
.br
.ti -1c
.RI "static const std::string & \fBResourcesPath\fP ()"
.br
.ti -1c
.RI "static const std::string & \fBDataPath\fP ()"
.br
.ti -1c
.RI "static const std::string & \fBOutputPath\fP ()"
.br
.ti -1c
.RI "static const std::string & \fBConfigPath\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PIM380 from the source code\&.
