.TH "Coordinate" 3 "Tue Apr 9 2013" "Version 0.1" "PIM380" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coordinate \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCoordinate\fP (const int &x, const int &y)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PIM380 from the source code\&.
