.TH "OtherElem" 3 "Tue Apr 9 2013" "Version 0.1" "PIM380" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OtherElem \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBelem_name\fP"
.br
.ti -1c
.RI "int \fBelem_count\fP"
.br
.ti -1c
.RI "\fBOtherData\fP ** \fBother_data\fP"
.br
.ti -1c
.RI "\fBPlyOtherProp\fP * \fBother_props\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PIM380 from the source code\&.
