.TH "PlyFile" 3 "Tue Apr 9 2013" "Version 0.1" "PIM380" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlyFile \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILE * \fBfp\fP"
.br
.ti -1c
.RI "int \fBfile_type\fP"
.br
.ti -1c
.RI "float \fBversion\fP"
.br
.ti -1c
.RI "int \fBnelems\fP"
.br
.ti -1c
.RI "\fBPlyElement\fP ** \fBelems\fP"
.br
.ti -1c
.RI "int \fBnum_comments\fP"
.br
.ti -1c
.RI "char ** \fBcomments\fP"
.br
.ti -1c
.RI "int \fBnum_obj_info\fP"
.br
.ti -1c
.RI "char ** \fBobj_info\fP"
.br
.ti -1c
.RI "\fBPlyElement\fP * \fBwhich_elem\fP"
.br
.ti -1c
.RI "\fBPlyOtherElems\fP * \fBother_elems\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PIM380 from the source code\&.
