.TH "PlyProperty" 3 "Tue Apr 9 2013" "Version 0.1" "PIM380" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlyProperty \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBexternal_type\fP"
.br
.ti -1c
.RI "int \fBinternal_type\fP"
.br
.ti -1c
.RI "int \fBoffset\fP"
.br
.ti -1c
.RI "int \fBis_list\fP"
.br
.ti -1c
.RI "int \fBcount_external\fP"
.br
.ti -1c
.RI "int \fBcount_internal\fP"
.br
.ti -1c
.RI "int \fBcount_offset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PIM380 from the source code\&.
