.TH "PointSet" 3 "Tue Apr 9 2013" "Version 0.1" "PIM380" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PointSet \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPointSet\fP (const std::string &iFilename)"
.br
.ti -1c
.RI "void \fBLoadPlyFile\fP (const char *iFilename)"
.br
.ti -1c
.RI "void \fBLoadFromFile\fP (const std::string &iFilename)"
.br
.ti -1c
.RI "void \fBWriteToFile\fP (const std::string &iFilename)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PIM380 from the source code\&.
