.TH "VertexPOD" 3 "Tue Apr 9 2013" "Version 0.1" "PIM380" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VertexPOD \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBz\fP"
.br
.ti -1c
.RI "float \fBnx\fP"
.br
.ti -1c
.RI "float \fBny\fP"
.br
.ti -1c
.RI "float \fBnz\fP"
.br
.ti -1c
.RI "unsigned char \fBred\fP"
.br
.ti -1c
.RI "unsigned char \fBgreen\fP"
.br
.ti -1c
.RI "unsigned char \fBblue\fP"
.br
.ti -1c
.RI "unsigned char \fBalpha\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PIM380 from the source code\&.
